CREATE INDEX CLIENTID_INDEX ON individualqueryresult(CLIENTID);
CREATE INDEX ENCOUNTERID_INDEX ON individualqueryresult(ENCOUNTERID);
CREATE INDEX QUERYCOMPONENTCODE_INDEX ON individualqueryresult(QUERYCOMPONENTCODE);

CREATE INDEX CODE_LASTINDIVIDUALQUERYRESULTID ON consolidatedqueryresult(LASTINDIVIDUALQUERYRESULTID);
CREATE INDEX CODE_QUERYCOMPONENTCODE ON consolidatedqueryresult(QUERYCOMPONENTCODE);
CREATE INDEX CODE_RESULTFROM ON consolidatedqueryresult(RESULTFROM);
CREATE INDEX CODE_RESULTTO ON consolidatedqueryresult(RESULTTO);